[versions]
versionCode = "1"
versionName = "1.0"
androidLoadingDots = "1.3.2"
application = "8.5.1"
coreTesting = "2.2.0"
junit = "4.13.2"
kotlin = "2.0.0"
kotlinxCoroutinesTest = "1.8.1"
ksp = "2.0.0-1.0.24"
appcompat = "1.7.0"
circleimageview = "3.1.0"
composeBom = "2024.06.00"
constraintlayout = "2.1.4"
converterGson = "2.11.0"
coreKtx = "1.13.1"
country = "1.1.1"
firebaseAnalytics = "22.0.2"
firebaseAuth = "23.0.0"
firebaseBom = "33.1.2"
firebaseFirestore = "25.0.0"
firebaseStorage = "21.0.0"
glide = "4.16.0"
googleServices = "4.4.2"
gradle = "8.5.1"
hiltAndroid = "2.51.1"
hiltAndroidGradlePlugin = "2.51.1"
kotlinGradlePlugin = "1.6.21"
kotlinxCoroutines = "1.8.1"
lifecycle = "2.8.4"
loadingButtonAndroid = "2.3.0"
material = "1.12.0"
minSdk = "24"
mockitoCore = "5.12.0"
navigationCompose = "2.7.7"
playServicesAuth = "21.2.0"
retrofit = "2.11.0"
targetSdk = "34"
truth = "1.4.4"
viewpager2 = "1.1.0"
compileSdk = "34"
activity = "1.9.1"
googleid = "1.1.1"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
[plugins]
org-jetbrains-kotlin-android = {id = "org.jetbrains.kotlin.android", version.ref = "kotlin"}
com-android-application = {id = "com.android.application", version.ref = "application"}
com-google-devtools-ksp = {id = "com.google.devtools.ksp", version.ref = "ksp"}
com-google-dagger-hilt-android = {id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid"}
android-library = { id = "com.android.library", version.ref = "application" }
[libraries]
android-loading-dots = { module = "com.github.razaghimahdi:Android-Loading-Dots", version.ref = "androidLoadingDots" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigationCompose" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationCompose" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationCompose" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
country = { module = "com.github.nkuppan.country:country", version.ref = "country" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuth" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebaseAnalytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-storage = { module = "com.google.firebase:firebase-storage", version.ref = "firebaseStorage" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore", version.ref = "firebaseFirestore" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hiltAndroidGradlePlugin" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
loading-button-android = { module = "com.github.leandroborgesferreira:loading-button-android", version.ref = "loadingButtonAndroid" }
material = { module = "com.google.android.material:material", version.ref = "material" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleid" }
truth = { module = "com.google.truth:truth", version = "truth" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
